name: Kernel Module

on:
  push:
    branches: [ '*' ]
    paths:
    - 'kernel_module/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-20.04']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install kernel dependencies
      run: ./.github/scripts/install-kernel-dependencies.sh

    - name: Build kernel module
      run: |
        cd kernel_module
        make
